// Bundles the ES modules in js/ into js/app.bundle.js, a plain script.
// Browsers refuse to load modules from file:// pages, so the bundle is what lets
// index.html work when you simply double-click it. Run after editing anything in js/:
//   node tools/build.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const dir = join(dirname(fileURLToPath(import.meta.url)), '..', 'js');
const mods = new Map();
const order = [];

function parse(name) {
  const deps = [];
  const exported = [];
  const code = readFileSync(join(dir, `${name}.js`), 'utf8')
    .replace(/^import\s+\*\s+as\s+([\w$]+)\s+from\s+'\.\/([\w-]+)\.js';?/gm, (_, ns, dep) => {
      deps.push(dep);
      return `const ${ns} = __m.${dep};`;
    })
    .replace(/^import\s+\{([^}]*)\}\s+from\s+'\.\/([\w-]+)\.js';?/gm, (_, names, dep) => {
      deps.push(dep);
      return `const {${names.replace(/\s+as\s+/g, ': ')}} = __m.${dep};`;
    })
    .replace(/^export\s+((?:async\s+)?function\*?|const|let|class)\s+([\w$]+)/gm, (_, kind, id) => {
      exported.push(id);
      return `${kind} ${id}`;
    });
  const leftover = code.match(/^\s*(import|export)\b.*$/m);
  if (leftover) throw new Error(`${name}.js: unsupported syntax for the bundler: ${leftover[0].trim()}`);
  return { code, deps, exported };
}

function visit(name, stack = []) {
  if (order.includes(name)) return;
  if (stack.includes(name)) throw new Error(`Circular import: ${[...stack, name].join(' -> ')}`);
  if (!mods.has(name)) mods.set(name, parse(name));
  for (const dep of mods.get(name).deps) visit(dep, [...stack, name]);
  order.push(name);
}

visit('app');

const body = order
  .map((name) => {
    const { code, exported } = mods.get(name);
    return `\n// ---------- ${name}.js ----------\n__m.${name} = (() => {\n${code.trim()}\nreturn { ${exported.join(', ')} };\n})();\n`;
  })
  .join('');

const out = `// Generated by tools/build.mjs from the files in js/. Don't edit by hand.\n(() => {\n'use strict';\nconst __m = {};\n${body}})();\n`;
writeFileSync(join(dir, 'app.bundle.js'), out);
console.log(`Built js/app.bundle.js from ${order.length} modules (${(out.length / 1024).toFixed(1)} KB): ${order.join(', ')}`);
